---
title: "Personal Savings Analysis"
author: "Frances Hung"
date: "11/6/2018"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
require(TSA)
require(dplyr)
```

```{r}
# load the time series
savings = read.csv("savings.csv",header=TRUE, nrows=104)
savings = savings %>% select(2)
savings.test = savings[80:84,]
savings = savings[1:79,]
savings<-ts(savings, start=c(1955),frequency=4)

# plot the original time series with labels for quarters
plot(savings, xlab="Year (by Quarter)", 
     ylab= "Percent of Disposible Income", 
     main= "Time Series of Personal Savings in the US (1955-1980)")
points(y=savings,x=as.vector(time(savings)),pch=as.vector(season(savings)), cex=.75)
abline(mean(savings),0)
```
We took off the last 5 years because there was a huge drop due to a recession. Then we took off the last 5 observations in order to use them as test points at the end.


```{r,warning=FALSE,eval=FALSE}
# should we do a transformation?
boxcox = BoxCox.ar(savings)
boxcox$ci
lambda = boxcox$mle
lambda
```

The Boxcox output indicates that a transformation is not necessary in order to stabilize the variance.



```{r}
acf(savings)
pacf(savings)
```


```{r}
# use the eacf and best subsets to find a candidate model
eacf(savings)
sub = armasubsets(y=savings,nar=7,nma=7, y.name='test', ar.method='ols') 
plot(sub)
```

Without taking a difference, an AR(1) process is a good candidate for our data.

```{r}
# take a difference of the series
diffs = (savings - zlag(savings))[2:79]
plot(diffs, type="o")
abline(0,0)
```





```{r}
# find candidate models for the differenced series
eacf(diffs)
best.subsets = armasubsets(y=diffs,nar=7,nma=7, y.name='test', ar.method='ols') 
plot(best.subsets)
```




```{r}
diffs<-(savings-zlag(savings))
fit<-lm(savings~diffs)
#predicts<-predict.lm(fit)
plot(diffs)
resids<-rstudent(fit)
hist(resids)
acf(resids)
pacf(resids,lag=90)

ar(diffs[3:length(diffs)-1],order.max=2,AIC=F,method="yw")
arima(savings,order=c(2,1,0),method='ML')
eacf(diffs[3:length(diffs)-1])
```


